config/routes.rb
Store::Application.routes.draw do
  resources :tasks

  resources :products
  
  match "area_chart" => "products#area_chart"  
  match "pie_chart" => "products#pie_chart"
  match "bar_chart" => "products#bar_chart"
  match "candlestick_chart" => "products#candlestick_chart"
  match "annotated_time_line" => "products#annotated_time_line"
  match "column_chart" => "products#column_chart"
  match "combo_chart" => "products#combo_chart"
  match "guage" => "products#guage"
  match "line_chart" => "products#line_chart"
  match "scatter_chart" => "products#scatter_chart"  
  match "table" => "products#table"

   root :to => 'products#combo_chart'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, :notice => 'Task was successfully created.' }
        format.json { render :json => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, :notice => 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Task</legend>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :deadline, :class => 'control-label' %>
      <div class="controls">
        <%= f.datetime_select :deadline, :class => 'datetime_select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :status, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', tasks_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/tasks/edit.html.erb
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Description</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= link_to task.description, task_path(task) %></td>
        <td><%= task.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', task_path(task), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_task_path, :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<p>
  <b>Description</b><br>
  <%= @task.description %>
</p>

<p>
  <b>Deadline</b><br>
  <%= @task.deadline %>
</p>

<p>
  <b>Status</b><br>
  <%= @task.status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', tasks_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_task_path(@task), :class => 'btn' %>
  <%= link_to 'Delete', task_path(@task), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>